# Generated by Django 4.2.7 on 2023-11-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_club_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
