# Generated by Django 4.2.7 on 2023-11-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.league'),
        ),
    ]
