# Generated by Django 4.2.7 on 2023-12-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_comment_results_alter_league_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment Panel'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
