# Generated by Django 4.2.7 on 2023-12-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_favoritescalendar_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, choices=[('1', 'Home Team Wins'), ('2', 'Away Team Wins'), ('X', 'Draw')], max_length=10, null=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.match')),
            ],
            options={
                'verbose_name_plural': 'Bets',
            },
        ),
    ]
