# Generated by Django 4.2.7 on 2024-01-02 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0009_bet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={},
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='bet',
            new_name='match',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_prediction',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user_prediction',
        ),
        migrations.AddField(
            model_name='bet',
            name='choice',
            field=models.CharField(blank=True, choices=[('1', 'Home Team Wins'), ('X', 'Draw'), ('2', 'Away Team Wins')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
