# Generated by Django 4.2.7 on 2024-01-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_bet_options_rename_bet_bet_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_count_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_count_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_count_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='result',
            field=models.CharField(blank=True, choices=[('1', 'Home Team Wins'), ('X', 'Draw'), ('2', 'Away Team Wins')], max_length=1, null=True),
        ),
    ]
