# Generated by Django 4.2.7 on 2024-01-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_bet_bet_count_away_bet_bet_count_draw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet_count_away',
            new_name='away_team_win',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='bet_count_draw',
            new_name='draw',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='bet_count_home',
            new_name='home_team_win',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='choice',
        ),
    ]
